adds calendar of meetings to community page
holoviz/holoviz pull request #344
Opened 2022-12-22 12:38 UTC by droumis

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/6613202/209136060-cd61c050-6c8f-40ae-97e0-144b5138b5bc.png">

2022-12-22 15:05 UTC, maximlt requested changes
Oh that's going to be nice!

Made some minor comments. If you feel like I think there are a few changes to be made to this page that could improve it:
- It feels like it has quite a lot of text. For instance I prefer [Dask's page](https://docs.dask.org/en/stable/support.html). So I'd say feel free to remove anything that you find superfluous :)
- The page recommend first to have a look a StackOverflow. I think our updated recommendation would strongly steer users towards Discourse.
- It's missing Panel's twitter handle and it'd be nice to turn these handles into proper links.

One last thing, the *Operating Guide* also mentions these meetings (not the docs one actually). I guess that should be mentioned in one place only and the *Community* page feels like the right one, could you replace mentions of these meetings in the *Operating Guide* by a link to the *Community Page*?

2022-12-22 15:05 UTC, maximlt commented on doc/community.rst
> +  - General HoloViz meeting: This occurs biweekly on Fridays and is the best option for new members to join.
Could you link to the meeting notes? I think they're all under the same HackMd now, if so that would be just one link above or below this list. I think that's useful for people to see what is usually being discussed.

2022-12-22 15:05 UTC, maximlt commented on doc/community.rst
> +  - General HoloViz meeting: This occurs biweekly on Fridays and is the best option for new members to join.
Somewhat unrelated to this PR but actually list items in Markdown should not be indented, when they are they're parsed as a block or quote (I'm not sure). See how it looks now https://holoviz.org/community.html

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/35924738/209160923-2f97ac81-0b3e-4b43-9807-4b752dce3f72.png">

It'd be nice if you could fix those too :)

2022-12-30 15:33 UTC, droumis commented
@maximlt, I reworded and simplified most of the community page. If you like it we can merge now

2022-12-30 15:38 UTC, maximlt commented on doc/about.rst
> +`Project Governance <https://github.com/holoviz/holoviz/blob/master/doc/governance/project-docs/GOVERNANCE.md>`_,
```suggestion
`Project Governance <https://github.com/holoviz/holoviz/blob/main/doc/governance/project-docs/GOVERNANCE.md>`_, 
```

2022-12-30 15:39 UTC, maximlt approved these changes
I really like the intro of the Community page 👍

2022-12-30 15:39 UTC, merged